### ISSUE TITLE
Speak The Code

### ISSUE THREAD

**Issue by annadecarle** [annadecarle/components-on-a-grid#1]
[decarle-anna-speak-the-answers.m4a.zip](https://github.com/annadecarle/components-on-a-grid/files/7220796/decarle-anna-speak-the-answers.m4a.zip)

@thatkidmadrid

**Comment by thatkidmadrid** [comment]
Thanks for sending this, but this is not the best way to read out css

Please check out the activity we did in class and the accompanying videos to see what I mean

https://learn-the-web.algonquindesign.ca/courses/web-design-2/speak-your-code/

I will still give you full marks, but I encourage you to take another look at the lesson
